# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "0 8 1 * *"
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Run a one-line script
      run: ./scripts/update_config.py
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token:  ${{ secrets.GITHUB_TOKEN }}

