# https://docs.github.com/en/actions/

name: update-nuke-versions

on:
  schedule:
    - cron: "0 8 1 * *"
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update nuke versions
        run: make -B
      - name: Git commit
        run: |
          git config --global user.name 'CI User'
          git config --global user.email '<>'
          ./scripts/ci_commit.sh
      - name: Github push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
