# This is a basic workflow to help you get started with Actions

name: update-nuke-versions

on:
  schedule:
    - cron: "0 8 1 * *"
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        then pip install -r requirements.txt
    - name: Update nuke versions
      run: make -B
    - name: Git commit
      run: ./scripts
    - name: Github push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token:  ${{ secrets.GITHUB_TOKEN }}

