# https://docs.github.com/en/actions/

name: update-nuke-versions

on:
  schedule:
    - cron: "0 8 1 * *"
  push:
    branches: [master]
  pull_request:
    paths:
      - requirements.txt
      - scripts/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update nuke versions
        run: make -B
      - name: Git commit
        if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"          
          ./scripts/ci_commit.sh
      - name: Github push
        if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
